script: bundle exec rake

bundler_args: --without docs release benchmark

branches:
  only:
  - master

rvm:
- 1.9.3
- 2.0.0
- 2.1.2
- jruby

gemfile:
- Gemfile

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9967f9fc130ccb637a9
    on_success: change
    on_failure: always
    on_start: false
